<div class="container mt-2">
    <div class="page-banner-content">
        <h1 class="c-black fs-1"><?= $title ?></h1>
        <ul>
            <li class="c-gray fs-08"><a href="/" class="c-gray url-link">Inicio</a></li>
            <li class="fs-08"><?= $title ?></li>
        </ul>
    </div>
</div>

<!--Start Academic Details Area-->
<div class="academics-details-area pt-100 pb-70">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="academics-details">
                    <div class="details">
                        <h2>Becas por Convenios disponibles en México</h2>
                        <p>Actualmente hemos creado convenios con organizaciones públicas, privadas y de asistencia social, con el propósito de brindar un servicio de calidad y de fortalecer la creación de redes y comunidades de intercambio de valores. Algunas de ellas son:</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="detgails-right-content">
                    <div class="related-download">
                        <ul>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/KADIMA.pdf" target="_blank"><i class="flaticon-pdf-file"></i>1. Asociación civil para personas con necesidades especiales y/o discapacidad <span class="c-blue text-bold">"KADIMA"</span></a><br><a href="becas/KADIMA.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_Asociacion.pdf" target="_blank"><i class="flaticon-pdf-file"></i>2. Asociación Mexicana de Parkinson, A.C. <span class="c-blue text-bold">(AMPAC)</span></a><br><a href="becas/Becas_Asociacion.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/becas_astinvi.pdf" target="_blank"><i class="flaticon-pdf-file"></i>3. Asociación Sindical de Trabajadores del Instituto de Vivienda de la Ciudad de México <span class="c-blue text-bold">(ASTINVI)</span></a><br><a href="becas/becas_astinvi.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/bachillerato_tecnologico_tultitlan.pdf" target="_blank"><i class="flaticon-pdf-file"></i>4. Bachillerato Tecnológico Tultitlán</a><br><a href="becas/bachillerato_tecnologico_tultitlan.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Beca_Casa_de_los_Amigos.pdf" target="_blank"><i class="flaticon-pdf-file"></i>5. Casa de los Amigos, A.C.</a><br><a href="becas/Beca_Casa_de_los_Amigos.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>

                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/casa_nuevo.pdf" target="_blank"><i class="flaticon-pdf-file"></i>6. Casa Nuevo Empezar</a><br><a href="becas/casa_nuevo.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/CENTRO_ASISTENCIA_SOCIAL_AC.pdf" target="_blank"><i class="flaticon-pdf-file"></i>7. Centro de Asistencia Social, A.C.</a><br><a href="becas/CENTRO_ASISTENCIA_SOCIAL_AC.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Beca_cbtis_50.pdf" target="_blank"><i class="flaticon-pdf-file"></i>8. Centro de Bachillerato Tecnológico Industrial y de Servicios No. 50 <span class="c-blue text-bold">(CBTIS 50)</span></a><br><a href="becas/Beca_cbtis_50.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Beca_ANGELES_DE_LA_LUZ.pdf" target="_blank"><i class="flaticon-pdf-file"></i>9. Centro para el Desarrollo Integral a la Discapacidad <span class="c-blue text-bold">“ÁNGELES DE LUZ A.C.”</span></a><br><a href="becas/Beca_ANGELES_DE_LA_LUZ.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_CIJ.pdf" target="_blank"><i class="flaticon-pdf-file"></i>10. Centros de Integración Juvenil A.C. Nacional <span class="c-blue text-bold">(CIJ)</span></a><br><a href="becas/Becas_CIJ.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>

                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_Convenios_Cetis.pdf" target="_blank"><i class="flaticon-pdf-file"></i>11. <span class="c-blue text-bold">"CETIS"</span> de la CDMX</a><br><a href="becas/Becas_Convenios_Cetis.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Clinica_Lacaniana.pdf" target="_blank"><i class="flaticon-pdf-file"></i>12. Clínica Psicopedagógica Lacaniana</a><br><a href="becas/Clinica_Lacaniana.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/colegio_bachilleres.pdf" target="_blank"><i class="flaticon-pdf-file"></i>13. Colegio de Bachilleres</a><br><a href="becas/colegio_bachilleres.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/colegio_galileo.pdf" target="_blank"><i class="flaticon-pdf-file"></i>14. Colegio Galileo Galilei</a><br><a href="becas/colegio_galileo.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/COLEGIO_MEXICANO_DE_SUICIDIOLOGOS.pdf" target="_blank"><i class="flaticon-pdf-file"></i>15. Colegio Mexicano de Suicidiólogos, S.C.</a><br><a href="becas/COLEGIO_MEXICANO_DE_SUICIDIOLOGOS.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>

                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_Convenios_conalep.pdf" target="_blank"><i class="flaticon-pdf-file"></i>16. Con los siguientes <span class="c-blue text-bold">CONALEP</span><br>Conalep V Iztapalapa, Conalep Plantel del Sol, Conalep Tlanepantla Plantel III, Conalep Gustavo A. Madero II</a><br><a href="becas/Becas_Convenios_conalep.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/casa_ara.pdf" target="_blank"><i class="flaticon-pdf-file"></i>17. Consorcio de Ingeniería Integral Casas ARA</a><br><a href="becas/casa_ara.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/CAMARA_DE_DIPUTADOS.pdf" target="_blank"><i class="flaticon-pdf-file"></i>18. Cámara de Diputados</a><br><a href="becas/CAMARA_DE_DIPUTADOS.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_Adultos_Mayores.pdf" target="_blank"><i class="flaticon-pdf-file"></i>19. <span class="c-blue text-bold">"DIRECCIÓN GENERAL DEL INSTITUTO PARA LA ATENCIÓN A LOS ADULTOS MAYORES DEL D.F."</span></a><br><a href="becas/Becas_Adultos_Mayores.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_Comite_PRI.pdf" target="_blank"><i class="flaticon-pdf-file"></i>20. El Comité Directivo PRI CDMX</a><br><a href="becas/Becas_Comite_PRI.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>

                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/internado_infantil.pdf" target="_blank"><i class="flaticon-pdf-file"></i>21. El Internado Infantil Guadalupano A.C.</a><br><a href="becas/internado_infantil.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/sanatorio_agustin.pdf" target="_blank"><i class="flaticon-pdf-file"></i>22. El Sanatorio San Agustín</a><br><a href="becas/sanatorio_agustin.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_ECTESM.pdf" target="_blank"><i class="flaticon-pdf-file"></i>23. Estructura Ciudadana para el Trabajo, la Educación y la Salud en México, A.C.</a><br><a href="becas/Becas_ECTESM.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_FGR.pdf" target="_blank"><i class="flaticon-pdf-file"></i>24. Fiscalía General de la República <span class="c-blue text-bold">"(FGR)"</span></a><br><a href="becas/Becas_FGR.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_Fundacion_Centro_Historico.pdf" target="_blank"><i class="flaticon-pdf-file"></i>25. Fundación Centro Histórico de la Ciudad de México</a><br><a href="becas/Becas_Fundacion_Centro_Historico.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>

                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Beca_FUCAM.pdf" target="_blank"><i class="flaticon-pdf-file"></i>26. Fundación de Cáncer de Mama “FUCAM”</a><br><a href="becas/Beca_FUCAM.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_FEM.pdf" target="_blank"><i class="flaticon-pdf-file"></i>27. Fundación de Emprendedoras Mexicanas, A.C.</a><br><a href="becas/Becas_FEM.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_Convenios_Fundacion_Semilla.pdf" target="_blank"><i class="flaticon-pdf-file"></i>28. Fundación <span class="c-blue text-bold">SEMILLAS DE AMOR</span></a><br><a href="becas/Becas_Convenios_Fundacion_Semilla.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Convenio_Teleton.pdf" target="_blank"><i class="flaticon-pdf-file"></i>29. Fundación Teletón México, A.C.</a><br><a href="becas/Convenio_Teleton.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/GRUPO_DIAGNÓSTICO_MÉDICO_PROA.pdf" target="_blank"><i class="flaticon-pdf-file"></i>30. Grupo Diagnóstico Médico <span class="c-blue text-bold">"PROA"</span></a><br><a href="becas/GRUPO_DIAGNÓSTICO_MÉDICO_PROA.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>

                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Beccas_Grupo_Lala.pdf" target="_blank"><i class="flaticon-pdf-file"></i>31. <span class="c-blue text-bold">"GRUPO LALA"</span></a><br><a href="becas/Beccas_Grupo_Lala.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/hospital_homeopatico.pdf" target="_blank"><i class="flaticon-pdf-file"></i>32. Hospital Nacional Homeopático</a><br><a href="becas/hospital_homeopatico.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Beca_ASTINVI.pdf" target="_blank"><i class="flaticon-pdf-file"></i>33. Instituto de la Vivienda de la Ciudad de México <span class="c-blue text-bold">"ASTINVI"</span></a><br><a href="becas/Beca_ASTINVI.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_ISSSTE.pdf" target="_blank"><i class="flaticon-pdf-file"></i>34. Instituto de Seguridad y Servicios Sociales de los Trabajadores del Estado <span class="c-blue text-bold">(ISSSTE)</span></a><br><a href="becas/Becas_ISSSTE.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Convenio_IMJUVE.pdf" target="_blank"><i class="flaticon-pdf-file"></i>35. Instituto Mexicano de la Juventud <span class="c-blue text-bold">"IMJUVE"</span></a><br><a href="becas/Convenio_IMJUVE.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>

                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_IMP.pdf" target="_blank"><i class="flaticon-pdf-file"></i>36. Instituto Mexicano del Petróleo <span class="c-blue text-bold">(IMP)</span></a><br><a href="becas/Becas_IMP.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/IMJUC.pdf" target="_blank"><i class="flaticon-pdf-file"></i>37. Instituto Municipal de la Juventud de Cuautitlán Izcalli <span class="c-blue text-bold">"IMJUC"</span></a><br><a href="becas/IMJUC.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/INAPAM_160418.pdf" target="_blank"><i class="flaticon-pdf-file"></i>38. Instituto Nacional de las Personas Adultas Mayores <span class="c-blue text-bold">"(INAPAM)"</span></a><br><a href="becas/INAPAM_160418.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/InstitutoNacionalMigracion.pdf" target="_blank"><i class="flaticon-pdf-file"></i>39. Instituto Nacional de Migración</a><br><a href="becas/InstitutoNacionalMigracion.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/instituto_psiquiatria_ramon.pdf" target="_blank"><i class="flaticon-pdf-file"></i>40. Instituto Nacional de Psiquiatría Ramón De La Fuente Muñiz "SECCIÓN 95"</a><br><a href="becas/instituto_psiquiatria_ramon.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>

                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/instituto-pedagogico-escolar-ipem.pdf" target="_blank"><i class="flaticon-pdf-file"></i>41. Instituto Pedagógico Escolar México <span class="c-blue text-bold">(IPEM)</span></a><br><a href="becas/instituto-pedagogico-escolar-ipem.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/la_casa_de_la_sal.pdf" target="_blank"><i class="flaticon-pdf-file"></i>42. La casa de la sal A.C.</a><br><a href="becas/la_casa_de_la_sal.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Municipio_Cuautitlan.pdf" target="_blank"><i class="flaticon-pdf-file"></i>43. Municipio de Cuautitlán Izcalli <span class="c-blue text-bold">"MUNICIPIO"</span></a><br><a href="becas/Municipio_Cuautitlan.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Municipio_Tultitlan.pdf" target="_blank"><i class="flaticon-pdf-file"></i>44. Municipio de Tulltitlán</a><br><a href="becas/Municipio_Tultitlan.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/nueva_alianza_cdmx.pdf" target="_blank"><i class="flaticon-pdf-file"></i>45. Nueva Alianza Ciudad de México</a><br><a href="becas/nueva_alianza_cdmx.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>

                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_Pemex.pdf" target="_blank"><i class="flaticon-pdf-file"></i>46. Petróleos Mexicanos <span class="c-blue text-bold">(PEMEX)</span></a><br><a href="becas/Becas_Pemex.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/becas_pro_merc_df_sur.pdf" target="_blank"><i class="flaticon-pdf-file"></i>47. Pro merc DF sur, S.A. DE C.V.</a><br><a href="becas/becas_pro_merc_df_sur.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_Programa_Refugiados.pdf" target="_blank"><i class="flaticon-pdf-file"></i>48. Programa Casa Refugiados A.C.</a><br><a href="becas/Becas_Programa_Refugiados.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/secretaria_bienestar.pdf" target="_blank"><i class="flaticon-pdf-file"></i>49. Secretaría de Bienestar</a><br><a href="becas/secretaria_bienestar.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/sct.pdf" target="_blank"><i class="flaticon-pdf-file"></i>50. Secretaría de comunicaciones y transportes</a><br><a href="becas/sct.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>

                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Secretaria_defensa.pdf" target="_blank"><i class="flaticon-pdf-file"></i>51. Secretaría de Defensa Nacional</a><br><a href="becas/Secretaria_defensa.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/sener.pdf" target="_blank"><i class="flaticon-pdf-file"></i>52. Secretaría de Energía <span class="c-blue text-bold">"SENER"</span></a><br><a href="becas/sener.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/SHCP.pdf" target="_blank"><i class="flaticon-pdf-file"></i>53. Secretaría de Hacienda y Crédito Público <span class="c-blue text-bold">"SCHP"</span></a><br><a href="becas/SHCP.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Secretaria_Mujeres_CDMX.pdf" target="_blank"><i class="flaticon-pdf-file"></i>54. Secretaría de las Mujeres de la Ciudad de México</a><br><a href="becas/Secretaria_Mujeres_CDMX.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Secretaria_marina.pdf" target="_blank"><i class="flaticon-pdf-file"></i>55. Secretaría de Marina</a><br><a href="becas/Secretaria_marina.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>

                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_SAT.pdf" target="_blank"><i class="flaticon-pdf-file"></i>56. Servicio de Administración Tributaria <span class="c-blue text-bold">"(SAT)"</span></a><br><a href="becas/Becas_SAT.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/SESAJ.pdf" target="_blank"><i class="flaticon-pdf-file"></i>57. Sindicato de empleados del Servicio de Anales de Jurisprudencia <span class="c-blue text-bold">(SESAJ)</span></a><br><a href="becas/SESAJ.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_UNAM.pdf" target="_blank"><i class="flaticon-pdf-file"></i>58. Sindicato de Trabajadores de la Universidad Nacional Autónoma de México <span class="c-blue text-bold">UNAM</span></a><br><a href="becas/Becas_UNAM.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_Poder_Judicial.pdf" target="_blank"><i class="flaticon-pdf-file"></i>59. Sindicato de Trabajadores del Poder Judicial de la Ciudad de México</a><br><a href="becas/Becas_Poder_Judicial.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Convenio_INEA33.pdf" target="_blank"><i class="flaticon-pdf-file"></i>60. Sindicato del <span class="c-blue text-bold">"INEA 33"</span></a><br><a href="becas/Convenio_INEA33.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>

                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_SME.pdf" target="_blank"><i class="flaticon-pdf-file"></i>61. Sindicato Mexicano de Electricistas del D.F. <span class="c-blue text-bold">(SME)</span></a><br><a href="becas/Becas_SME.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_Sindicato_HospitalBenitoJuarez.pdf" target="_blank"><i class="flaticon-pdf-file"></i>62. Sindicato Nacional de Trabajadores de la Secretaría de Salud <span class="c-blue text-bold">"HOSPITAL JUÁREZ DE MÉXICO"</span></a><br><a href="becas/Becas_Sindicato_HospitalBenitoJuarez.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/becas_secretaria_de_salud_seccion_93.pdf" target="_blank"><i class="flaticon-pdf-file"></i>63. Sindicato Nacional de Trabajadores de la Secretaría de Salud en su <span class="c-blue text-bold">"SECCIÓN 93"</span></a><br><a href="becas/becas_secretaria_de_salud_seccion_93.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_IMSS.pdf" target="_blank"><i class="flaticon-pdf-file"></i>64. Sindicato Nacional de Trabajadores del Seguro Social <span class="c-blue text-bold">(IMSS NACIONAL)</span></a><br><a href="becas/Becas_IMSS.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/SINDICATO_DEL_METRO.pdf" target="_blank"><i class="flaticon-pdf-file"></i>65. Sindicato Nacional de Trabajadores del Sistema de Transporte Colectivo <span class="c-blue text-bold">(METRO)</span></a><br><a href="becas/SINDICATO_DEL_METRO.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>                            

                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/convenio-sindicato-unico-trabajadores-cdmx.pdf" target="_blank"><i class="flaticon-pdf-file"></i>66. Sindicato Único de Trabajadores de la Ciudad de México</a><br><a href="becas/convenio-sindicato-unico-trabajadores-cdmx.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Beca_GEA_Gonzalez.pdf" target="_blank"><i class="flaticon-pdf-file"></i>67. Sindicato Único de Trabajadores del Hospital General Dr. Manuel GEA González</a><br><a href="becas/Beca_GEA_Gonzalez.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Convenio_Seguro_Popular.pdf" target="_blank"><i class="flaticon-pdf-file"></i>68. Sistema de Protección Social en Salud del Distrito Federal <span class="c-blue text-bold">(SEGURO POPULAR)</span></a><br><a href="becas/Convenio_Seguro_Popular.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            <li data-aos="fade-right" data-aos-easing="ease-in-sine" data-aos-duration="1000" data-aos-once="true"><a href="becas/Becas_Sistema_Penitenciario.pdf" target="_blank"><i class="flaticon-pdf-file"></i>69. Subsecretaría del Sistema Penitenciario D.F.</a><br><a href="becas/Becas_Sistema_Penitenciario.pdf" class="c-orange" target="_blank">Ver beca y convenio</a></li>
                            
                            
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="row align-items-center">
                    <img src="assets/images/scholarships/IMAGEN_DE BECAS.png" alt="Image">
                </div>
            </div>

        </div>
    </div>
</div>
<!--End Academic Details Area-->