<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Odor - Vape Store WooCommerce HTML Template</title>
    <!-- Favicon img -->
    <link rel="shortcut icon" href="<?= base_url() ?>/assets/images/favicon.png">
    <!-- Bootstarp min css -->
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/bootstrap.min.css">
    <!-- All min css -->
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/all.min.css">
    <!-- Swiper bundle min css -->
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/swiper-bundle.min.css">
    <!-- Magnigic popup css -->
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/magnific-popup.css">
    <!-- Animate css -->
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/animate.css">
    <!-- Nice select css -->
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/nice-select.css">
    <!-- Style css -->
    <link rel="stylesheet" href="<?= base_url() ?>/assets/css/style.css">
</head>

<body>
  <!-- Loader -->
  <div id="loading1" class="loading-invisible" style="display:none;">
        <div class="loading-spinner">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: none; display: block; shape-rendering: auto;" width="204px" height="204px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
                <circle cx="50" cy="50" r="0" fill="none" stroke="#013369" stroke-width="3">
                    <animate attributeName="r" repeatCount="indefinite" dur="1.282051282051282s" values="0;40" keyTimes="0;1" keySplines="0 0.2 0.8 1" calcMode="spline" begin="0s"></animate>
                    <animate attributeName="opacity" repeatCount="indefinite" dur="1.282051282051282s" values="1;0" keyTimes="0;1" keySplines="0.2 0 0.8 1" calcMode="spline" begin="0s"></animate>
                </circle>
                <circle cx="50" cy="50" r="0" fill="none" stroke="#00263d" stroke-width="3">
                    <animate attributeName="r" repeatCount="indefinite" dur="1.282051282051282s" values="0;40" keyTimes="0;1" keySplines="0 0.2 0.8 1" calcMode="spline" begin="-0.641025641025641s"></animate>
                    <animate attributeName="opacity" repeatCount="indefinite" dur="1.282051282051282s" values="1;0" keyTimes="0;1" keySplines="0.2 0 0.8 1" calcMode="spline" begin="-0.641025641025641s"></animate>
                </circle>
                <!-- [ldio] generated by https://loading.io/ -->
            </svg>
            <span id="loadig-text-1" class="loading-text c-white">Procesando, espere un momento....</span>
        </div>
    </div>
